# empty url and relative needed for ipfs
baseurl = ""
relativeurls = true
languageCode = "en-us"
theme = "nonagon"

[Params]
name = "Gregory Hill"
github = "https://github.com/gregdhill"
twitter = "https://twitter.com/gregorydhill"
scholar = "https://scholar.google.co.uk/citations?user=OoKiidsAAAAJ&hl=en"
image = "profile.jpg"
description = "Interested in Blockchains, Cryptography and Distributed Systems."
keywords = "computer, security, ethical hacker, researcher, inventor, abertay, dundee, edinburgh, machine learning, mathematics, cryptography, blockchains, reverse engineering, linux, programming, scotland, greg hill"

[[Params.Home.Links]]
url = "posts"
icon = "fa-archive"

[[Params.Home.Links]]
url = "tags"
icon = "fa-tag"

[[Params.Home.Links]]
url = "projects"
icon = "fa-file"

[[Params.Social.Links]]
url = "https://github.com/gregdhill"
icon = "fa-github"

[[Params.Social.Links]]
url = "https://twitter.com/gregorydhill"
icon = "fa-twitter"

[[Params.Social.Links]]
url = "https://scholar.google.co.uk/citations?user=OoKiidsAAAAJ&hl=en"
icon = "fa-graduation-cap"

# needed for bitcoin github snippets
[markup.goldmark.renderer]
unsafe = true