baseURL = "https://greghill.io"
title = "Greg Hill"
theme = "tale"

languageCode = "en-gb"

[Author]
    name = "Greg Hill"

[markup.highlight]
codeFences = true
noClasses = false

[menu]
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    title = "Projects"
    url = "/projects/"
    weight = 0
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    title = "Posts"
    url = "/posts/"
    weight = 0
