baseurl = "/"
languageCode = "en-us"
theme = "nonagon"
pygmentsCodeFences = true

[Params]
    firstname = "Gregory"
    lastname = "Hill"
    github = "https://github.com/gregdhill"
    twitter = "https://twitter.com/gregorydhill"
    scholar = "https://scholar.google.co.uk/citations?user=OoKiidsAAAAJ&hl=en"
    image = "profile.jpg"
    description = "Interested in Blockchains, Cryptography and Distributed Systems."
    keywords = "computer, security, ethical hacker, researcher, inventor, abertay, dundee, edinburgh, machine learning, mathematics, cryptography, blockchains, reverse engineering, linux, programming, scotland, greg hill"

[Author]
    name = "Greg"